# Generated by Django 5.0.3 on 2024-08-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='60:00', max_length=100, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('calories_burned', models.PositiveIntegerField()),
                ('gif', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
