# Generated by Django 5.0.3 on 2024-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_userfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_data',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise_data',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
