# Generated by Django 5.0.3 on 2024-08-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_exercise_data_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfood',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userfood',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userfood',
            name='upated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
