# Generated by Django 5.0.3 on 2024-08-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_userfood_created_date_userfood_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfood',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfood',
            name='upated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
