# Generated by Django 5.0.3 on 2025-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_userfood_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='images')),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('certifications', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('job', models.CharField(choices=[('trainer', 'trainer'), ('nutritionist', 'nutritionist')], max_length=100, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
